### PR TITLE
Switch to OTP 23 compatible rocksdb

### PR DESCRIPTION
**Pull request by Vagabond**

### CODE REVIEW

**Review by evanmcc — APPROVED** [review]
do we have these waiting to be upstreamed?

**Comment by Vagabond** [comment]
> do we have these waiting to be upstreamed?

It's one commit that's a shitty hack to fix crosscompiling on arm64, it would require working with Facebook to fix it.

**Comment by Vagabond** [comment]
https://gitlab.com/Vagabond1/erlang-rocksdb/-/commit/12be329266b9fe24371dadef091921bfefa23c30 for reference

**Review by JayKickliter — APPROVED** [review]
I can confirm that this builds on amd64 with OTP-23, but I have not tried cross-compiling it

**Pull request merged**
